IF
AreaCheck("RTF142")
See("CVSandr")
Global("SanRTFPlot4","GLOBAL",3)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogueNoSet([PC])
END

IF
AttackedBy([PC],DEFAULT)
THEN
RESPONSE #100
Enemy()
SetGlobal("RTLarlNumberThreeTimerPrep","LOCALS",1)
SetGlobalTimer("RTLarlNumberThreeDrankPotionTimer","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeCalledForHealing","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeGaveAwayPotion","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeTrueSight_Used","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeSpellDefense1_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeWeaponDefense_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeShield_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeTeleportField_On","LOCALS",0)
END

IF
See(NearestEnemyOf(Myself))
Global("RTLarlNumberThreeTimerPrep","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("RTLarlNumberThreeTimerPrep","LOCALS",1)
SetGlobalTimer("RTLarlNumberThreeDrankPotionTimer","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeCalledForHealing","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeGaveAwayPotion","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeTrueSight_Used","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeSpellDefense1_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeWeaponDefense_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeShield_On","LOCALS",0)
SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeTeleportField_On","LOCALS",0)
END

IF
!Detect(NearestEnemyOf(Myself))
CombatCounter(0)
THEN
RESPONSE #100
NoAction()
END

IF
	StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VOCALIZE)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_VOCALIZE)
END

IF
	See(NearestEnemyOf(Myself))
	!Range(NearestEnemyOf(Myself),10)
	HaveSpell(WIZARD_TIME_STOP)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_TIME_STOP)
END

IF
	Detect(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_TRUE_SIGHT)
	OR(2)
		!See(NearestEnemyOf(Myself))
		StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("RTLarlNumberThreeTrueSight_Used","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeTrueSight_Used","LOCALS",TWELVE_MINUTES)
		Spell(Myself,WIZARD_TRUE_SIGHT)
END

IF
	GlobalTimerExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
THEN
	RESPONSE #100
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",-1)
		Continue()
END

IF
	GlobalTimerExpired("RTLarlNumberThreeRTLarlNumberThreeSpellDefense1_On","LOCALS")
THEN
	RESPONSE #100
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",-1)
		Continue()
END

IF
	GlobalTimerExpired("RTLarlNumberThreeRTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS")
THEN
	RESPONSE #100
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",-1)
		Continue()
END

IF
	OR(10)
		SpellCastOnMe([GOODCUTOFF],WIZARD_TRUE_DISPEL_MAGIC)
		SpellCastOnMe([GOODCUTOFF],WIZARD_TRUE_DISPEL_MAGIC)
		SpellCastOnMe([GOODCUTOFF],CLERIC_DISPEL_MAGIC)
		SpellCastOnMe([GOODCUTOFF],WIZARD_BREACH)
		SpellCastOnMe([GOODCUTOFF],WIZARD_PIERCE_MAGIC)
		SpellCastOnMe([GOODCUTOFF],WIZARD_TRUE_DISPEL_MAGIC)
		SpellCastOnMe([GOODCUTOFF],WIZARD_WARDING_WHIP)
		SpellCastOnMe([GOODCUTOFF],WIZARD_RUBY_RAY_OF_REVERSAL)
		SpellCastOnMe([GOODCUTOFF],WIZARD_SPELL_STRIKE)
		SpellCastOnMe([GOODCUTOFF],INQUIS_DISPEL_MAGIC)
	OR(6)
		GlobalTimerNotExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
		GlobalTimerNotExpired("RTLarlNumberThreeRTLarlNumberThreeSpellDefense1_On","LOCALS")
		GlobalTimerNotExpired("RTLarlNumberThreeRTLarlNumberThreeWeaponDefense_On","LOCALS")
		GlobalTimerNotExpired("RTLarlNumberThreeRTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS")
		GlobalTimerNotExpired("RTLarlNumberThreeRTLarlNumberThreeShield_On","LOCALS")
		GlobalGT("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",0)
		SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",0)
		SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeSpellDefense1_On","LOCALS",0)
		SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeWeaponDefense_On","LOCALS",0)
		SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS",0)
		SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeShield_On","LOCALS",0)
END

IF
	SpellCastOnMe([GOODCUTOFF],WIZARD_TRUE_SIGHT)
	SpellCastOnMe([GOODCUTOFF],CLERIC_TRUE_SIGHT)
	SpellCastOnMe([GOODCUTOFF],INQUIS_TRUE_SIGHT)
	GlobalTimerNotExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",0)
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",-1)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_SIMULACRUM)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
	GlobalLT("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",96)
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_SIMULACRUM)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_PROJECT_IMAGE)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
	GlobalLT("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",84)
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_PROJECT_IMAGE)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MISLEAD)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Myself,STATE_POISONED)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
	GlobalLT("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",72)
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_MISLEAD)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_SHADOW_DOOR)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Myself,STATE_POISONED)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpecialDefenseUp","LOCALS")
	GlobalLT("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpecialDefenseUp","LOCALS",NINE_ROUNDS)
		IncrementGlobal("RTLarlNumberThreeRTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_SHADOW_DOOR)
		Continue()
END

IF
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
	!CheckStatGT(Myself,0,MINORGLOBE)
	GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",0)
		Continue()
END

IF
	HaveSpell(WIZARD_SPELL_TRAP)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	OR(5)
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.SORCERER]))
	!CheckStatGT(Myself,0,MINORGLOBE)
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",SIX_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_SPELL_TRAP)
END

IF
	HaveSpell(WIZARD_SPELL_TURNING)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	OR(5)
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.SORCERER]))
	!CheckStatGT(Myself,0,MINORGLOBE)
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",SIX_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_SPELL_TURNING)
END

IF
	HaveSpell(WIZARD_SPELL_DEFLECTION)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	OR(5)
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.SORCERER]))
	!CheckStatGT(Myself,0,MINORGLOBE)
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",SIX_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_SPELL_DEFLECTION)
END

IF
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	OR(5)
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.SORCERER]))
	!CheckStatGT(Myself,0,MINORGLOBE)
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",SIX_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

IF
	HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	OR(5)
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.SORCERER]))
	!CheckStatGT(Myself,0,MINORGLOBE)
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",SIX_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
END

IF
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellDefense1_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	OR(5)
		See(NearestEnemyOfType([0.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
		See(NearestEnemyOfType([0.0.0.CLERIC_ALL]))
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.SORCERER]))
	!CheckStatGT(Myself,0,MINORGLOBE)
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeSpellDefense1_On","LOCALS",SIX_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END

IF
	!HasImmunityEffects(Myself)
	GlobalTimerNotExpired("RTLarlNumberThreeWeaponDefense_On","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeWeaponDefense_On","LOCALS",0)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_ABSOLUTE_IMMUNITY)
	!GlobalTimerNotExpired("RTLarlNumberThreeWeaponDefense_On","LOCALS")
	OR(2)
		Range(NearestEnemyOf(Myself),4)
		AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeWeaponDefense_On","LOCALS",28)
		Spell(Myself,WIZARD_ABSOLUTE_IMMUNITY)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_IMPROVED_MANTLE)
	!GlobalTimerNotExpired("RTLarlNumberThreeWeaponDefense_On","LOCALS")
	OR(2)
		Range(NearestEnemyOf(Myself),4)
		AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeWeaponDefense_On","LOCALS",FOUR_ROUNDS)
		Spell(Myself,WIZARD_IMPROVED_MANTLE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MANTLE)
	!GlobalTimerNotExpired("RTLarlNumberThreeWeaponDefense_On","LOCALS")
	OR(2)
		Range(NearestEnemyOf(Myself),4)
		AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeWeaponDefense_On","LOCALS",FOUR_ROUNDS)
		Spell(Myself,WIZARD_MANTLE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!GlobalTimerNotExpired("RTLarlNumberThreeWeaponDefense_On","LOCALS")
	OR(2)
		Range(NearestEnemyOf(Myself),4)
		AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeWeaponDefense_On","LOCALS",FOUR_ROUNDS)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
END

IF
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("RTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	HaveSpell(WIZARD_FIRE_SHIELD_RED)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS",TWELVE_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END

IF
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("RTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS")
	GlobalLT("RTLarlNumberThreeNumDefenses","LOCALS",2)
	HaveSpell(WIZARD_FIRE_SHIELD_BLUE)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeFireRTLarlNumberThreeShield_On","LOCALS",TWELVE_MINUTES)
		IncrementGlobal("RTLarlNumberThreeNumDefenses","LOCALS",1)
		Spell(Myself,WIZARD_FIRE_SHIELD_BLUE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_IMPROVED_HASTE)
	!StateCheck(Myself,STATE_HASTED)
	CheckStat(Myself,0,IMPROVEDHASTE)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_IMPROVED_HASTE)
END

IF
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatGT(Myself,0,IMPROVEDHASTE)
		StateCheck(Myself,STATE_NORMAL)
	HaveSpell(WIZARD_IMPROVED_HASTE)
	See(NearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_HASTED)
	CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_IMPROVED_HASTE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_HASTE)
	!StateCheck(Myself,STATE_HASTED)
	CheckStat(Myself,0,IMPROVEDHASTE)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_HASTE)
END

IF
	See(NearestEnemyOf(Myself))
	OR(2)
		CheckStatGT(Myself,0,IMPROVEDHASTE)
		StateCheck(Myself,STATE_HASTED)
	HaveSpell(WIZARD_HASTE)
	See(NearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_HASTED)
	CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_HASTE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_STONE_SKIN)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_STONE_SKIN)
END

IF
	HaveSpell(WIZARD_RESIST_FEAR)
	OR(4)
		SpellCast([GOODCUTOFF],WIZARD_HORROR)
		SpellCast([GOODCUTOFF],WIZARD_SYMBOL_FEAR)
		SpellCastPriest([GOODCUTOFF],CLERIC_SYMBOL_FEAR)
		SpellCastPriest([GOODCUTOFF],CLERIC_CLOAK_OF_FEAR)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		Spell(Myself,WIZARD_RESIST_FEAR)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(WIZARD_RESIST_FEAR)
	See(NearestMyGroupOfType)
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_RESIST_FEAR)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_SHIELD)
	!GlobalTimerNotExpired("RTLarlNumberThreeShield_On","LOCALS")
	OR(2)
		See(NearestEnemyOfType([0.0.0.LONG_BOW]))
		See(NearestEnemyOfType([0.0.0.BARD_ALL]))
	OR(2)
		SpellCast([GOODCUTOFF],WIZARD_MAGIC_MISSILE)
		SpellCastOnMe([GOODCUTOFF],WIZARD_MAGIC_MISSILE)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeShield_On","LOCALS",ONE_HOUR)
		Spell(Myself,WIZARD_SHIELD)
END

IF
	HaveSpell(WIZARD_MIRROR_IMAGE)
	OR(5)
		Range([GOODCUTOFF.0.0.THIEF_ALL],10)
		Range([GOODCUTOFF.0.0.FIGHTER_ALL],10)
		Range([GOODCUTOFF.0.0.PALADIN],10)
		See([GOODCUTOFF.0.0.RANGER])
		HitBy([ANYONE],MISSILE)
	!StateCheck(Myself,STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
	See(NearestEnemyOf(Myself))
	Gender(LastSeenBy(Myself),SUMMONED)
	HaveSpell(WIZARD_DEATH_SPELL)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
	HaveSpell(WIZARD_POWER_WORD_KILL)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
END

IF
	HaveSpell(WIZARD_SYMBOL_DEATH)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)
END

IF
	HaveSpell(WIZARD_SYMBOL_STUN)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)
END

IF
	HaveSpell(WIZARD_SYMBOL_FEAR)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)
END

IF
	HaveSpell(WIZARD_SPHERE_OF_CHAOS)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_SPHERE_OF_CHAOS)
END

IF
	HaveSpell(WIZARD_POWER_WORD_SILENCE)
	See(NearestEnemyOf(Myself))
	OR(6)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),LONG_BOW)
		Class(LastSeenBy(Myself),SORCERER)
		InPartySlot(LastSeenBy(Myself),0)
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END

IF
	HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),3)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)
END

IF
	HaveSpell(WIZARD_POWER_WORD_KILL)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),60)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
END

IF
	HaveSpell(WIZARD_POWER_WORD_BLIND)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
END

IF
	HaveSpell(WIZARD_POWER_WORD_STUN)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!HasBounceEffects(LastSeenBy(Myself))
	HPLT(LastSeenBy(Myself),90)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
END

IF
	HaveSpell(WIZARD_IMPRISONMENT)
	See(NearestEnemyOf(Myself))
	RandomNum(2,1)
	NumInPartyAliveGT(2)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_IMPRISONMENT)
END

IF
	HaveSpell(WIZARD_FINGER_OF_DEATH)
	See(NearestEnemyOf(Myself))
	RandomNum(2,1)
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
	HaveSpell(WIZARD_PRISMATIC_SPRAY)
	See(NearestEnemyOf(Myself))
	RandomNum(3,1)
	!Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)
END

IF
	HaveSpell(WIZARD_ENERGY_DRAIN)
	See(NearestEnemyOf(Myself))
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)
END

IF
	HaveSpell(WIZARD_FLESH_TO_STONE)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FLESH_TO_STONE)
END

IF
	HaveSpell(WIZARD_TELEPORT_FIELD)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("RTLarlNumberThreeTeleportField_On","LOCALS")
	RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobalTimer("RTLarlNumberThreeTeleportField_On","LOCALS",TWENTY_MINUTES)
		Spell(Myself,WIZARD_TELEPORT_FIELD)
END

IF
	HaveSpell(WIZARD_LOWER_RESISTANCE)
	See(NearestEnemyOf(Myself))
	RandomNum(2,1)
	CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
	HaveSpell(WIZARD_CHAOS)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	RandomNum(2,1)
	!Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		Spell([ENEMY],WIZARD_CHAOS)
END

IF
	See(NearestEnemyOf(Myself))
	OR(5)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),LONG_BOW)
		Class(LastSeenBy(Myself),SORCERER)
	HaveSpell(WIZARD_FEEBLEMIND)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
	!Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)
END

IF
	HaveSpell(WIZARD_DOMINATION)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DOMINATION)
END

IF
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),5)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	HaveSpell(WIZARD_CONFUSION)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell([ENEMY],WIZARD_CONFUSION)
END

IF
	HaveSpell(WIZARD_SLOW)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!Range(LastSeenBy(Myself),10)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	HaveSpell(WIZARD_RAY_OF_ENFEEBLEMENT)
	!Range(LastSeenBy(Myself),10)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_RAY_OF_ENFEEBLEMENT)
END

IF
	HaveSpell(WIZARD_FINGER_OF_DEATH)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell([ENEMY],WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
	HaveSpell(WIZARD_MAZE)
	See(NearestEnemyOf(Myself))
	HPGT(LastSeenBy(Myself),50)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_MAZE)
END

IF
	HaveSpell(WIZARD_HORROR)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	RandomNum(4,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_HORROR)
END

IF
	HaveSpell(WIZARD_MORDENKAINENS_SWORD)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),5)
	NumCreatureLT([EVILCUTOFF.0.0.0.0.SUMMONED],7)
	RandomNum(4,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
	HaveSpell(WIZARD_CARRION)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),10)
	NumCreatureLT([EVILCUTOFF.0.0.0.0.SUMMONED],7)
	RandomNum(4,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_CARRION)
END

IF
	HaveSpell(WIZARD_CONE_OF_COLD)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	HaveSpell(WIZARD_CONTROL_UNDEAD)
	See(NearestEnemyOf(Myself))
	General(LastSeenBy(Myself),UNDEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_CONTROL_UNDEAD)
END

IF
	HaveSpell(WIZARD_DEATH_SPELL)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	NumCreatureGT([GOODCUTOFF],4)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
	HaveSpell(WIZARD_SUN_FIRE)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),3)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	HaveSpell(WIZARD_ICE_STORM)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),15)
	NumCreatureGT([GOODCUTOFF],4)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)
END

IF
	HaveSpell(WIZARD_DISINTEGRATE)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell([ENEMY],WIZARD_DISINTEGRATE)
END

IF
	HaveSpell(WIZARD_METEOR_SWARM)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),15)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_METEOR_SWARM)
END

IF
	HaveSpell(WIZARD_MELF_METEOR)
	See(NearestEnemyOf(Myself))
	!HasItem("BLAKBLAD",Myself)
	!HasItem("PHANBLAD",Myself)
	!HasItem("MELFMET",Myself)
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_MELF_METEOR)
END

IF
	HaveSpell(WIZARD_FIREBALL)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGICFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Range(LastSeenBy(Myself),10)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FIREBALL)
END

IF
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),10)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTELECTRICITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),6)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
	HaveSpell(WIZARD_DELAYED_BLAST_FIREBALL)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGICFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!Range(LastSeenBy(Myself),20)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DELAYED_BLAST_FIREBALL)
		RunAwayFrom(LastSeenBy(Myself),100)
END

IF
	HaveSpell(WIZARD_BURNING_HANDS)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGICFIRE)
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	HaveSpell(WIZARD_FLAME_ARROW)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
	HaveSpell(WIZARD_POLYMORPH_OTHER)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	HPGT(LastSeenBy(Myself),40)
	RandomNum(3,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_POLYMORPH_OTHER)
END

IF
	HaveSpell(WIZARD_MAGIC_MISSILE)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	HaveSpell(WIZARD_CHROMATIC_ORB)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	HaveSpell(WIZARD_TENSERS_TRANSFORMATION)
	See(NearestEnemyOf(Myself))
	OR(3)
		Range(LastSeenBy(Myself),5)
		HasItem("BLAKBLAD",Myself)
		HasItem("PHANBLAD",Myself)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_TENSERS_TRANSFORMATION)
END

IF
	HaveSpell(WIZARD_BLACK_BLADE_OF_DISASTER)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!HasItem("BLAKBLAD",Myself)
	!HasItem("PHANBLAD",Myself)
	!HasItem("MELFMET",Myself)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_BLACK_BLADE_OF_DISASTER)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	HaveSpell(WIZARD_PHANTOM_BLADE)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!HasItem("BLAKBLAD",Myself)
	!HasItem("PHANBLAD",Myself)
	!HasItem("MELFMET",Myself)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_PHANTOM_BLADE)
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	HaveSpell(CLERIC_FREE_ACTION)
	See(NearestEnemyOf(Myself))
	OR(3)
		StateCheck(Myself,STATE_HELPLESS)
		!CheckStat(Myself,0,WEB)
		!CheckStat(Myself,0,ENTANGLE)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_FREE_ACTION)
END

IF
	HaveSpell(CLERIC_SLOW_POISON)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_SLOW_POISON)
END

IF
	HaveSpell(CLERIC_NEUTRALIZE_POISON)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_NEUTRALIZE_POISON)
END

IF
	Detect(NearestEnemyOf(Myself))
	OR(6)
		!See(NearestEnemyOf(Myself))
		StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
		StateCheck(NearestEnemyOf(Myself),STATE_BLUR)
		Gender(NearestEnemyOf(Myself),ILLUSIONARY)
		HaveSpell(CLERIC_TRUE_SIGHT)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_TRUE_SIGHT)
END

IF
	HaveSpell(CLERIC_FREE_ACTION)
	See(NearestMyGroupOfType)
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
		!CheckStat(LastSeenBy(Myself),0,WEB)
		!CheckStat(LastSeenBy(Myself),0,ENTANGLE)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_NORMAL)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_FREE_ACTION)
END

IF
	HaveSpell(CLERIC_SLOW_POISON)
	See(NearestMyGroupOfType)
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_NORMAL)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)
END

IF
	HaveSpell(CLERIC_NEUTRALIZE_POISON)
	See(NearestMyGroupOfType)
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_NORMAL)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_NEUTRALIZE_POISON)
END

IF
	See(NearestMyGroupOfType)
	Range(LastSeenBy(Myself),10)
	!Range(NearestEnemyOf(Myself),5)
	HaveSpell(CLERIC_BLESS)
	!StateCheck(Myself,STATE_BLESS)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_BLESS)
END

IF
	HaveSpell(CLERIC_REMOVE_FEAR)
	See(NearestMyGroupOfType)
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)
END

IF
	OR(5)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),LONG_BOW)
		Class(LastSeenBy(Myself),SORCERER)
	!GlobalTimerNotExpired("RTLarlNumberThreeSpellArmorOn","LOCALS")
	!HasBounceEffects(Myself)
	!HasImmunityEffects(Myself)
	HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)
		SetGlobalTimer("RTLarlNumberThreeSpellArmorOn","LOCALS",TWENTY_MINUTES)
		ClearAllActions()
END

IF
	HaveSpell(CLERIC_BLADE_BARRIER)
	See(NearestEnemyOf(Myself))
	See(NearestMyGroupOfType)
	!Range(LastSeenBy(Myself),8)
	!GlobalTimerNotExpired("RTLarlNumberThreeBladeBarrierOn","LOCALS")
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_BLADE_BARRIER)
		SetGlobalTimer("RTLarlNumberThreeBladeBarrierOn","LOCALS",TWENTY_MINUTES)
		ClearAllActions()
END

IF
	HaveSpell(CLERIC_IRONSKIN)
	CheckStatLT(Myself,1,STONESKINS)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_IRONSKIN)
END

IF
	HaveSpell(CLERIC_PHYSICAL_MIRROR)
	!GlobalTimerNotExpired("RTLarlNumberThreeRTLarlNumberThreeMagicArmorOn","LOCALS")
	!HasBounceEffects(Myself)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_PHYSICAL_MIRROR)
		SetGlobalTimer("RTLarlNumberThreeRTLarlNumberThreeMagicArmorOn","LOCALS",TWENTY_MINUTES)
END

IF
	HaveSpell(CLERIC_DEATH_WARD)
	See(NearestEnemyOf(Myself))
	CheckStat(Myself,0,SCRIPTINGSTATE2)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_DEATH_WARD)
END

IF
	HaveSpell(CLERIC_ARMOR_OF_FAITH)
	!GlobalTimerNotExpired("RTLarlNumberThreeMagicArmorOn","LOCALS")
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)
		SetGlobalTimer("RTLarlNumberThreeMagicArmorOn","LOCALS",TWENTY_MINUTES)
		ClearAllActions()
END

IF
	HaveSpell(CLERIC_BARKSKIN)
	!GlobalTimerNotExpired("RTLarlNumberThreeMagicArmorOn","LOCALS")
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_BARKSKIN)
		SetGlobalTimer("RTLarlNumberThreeMagicArmorOn","LOCALS",TWENTY_MINUTES)
		ClearAllActions()
END

IF
	HaveSpell(CLERIC_REGENERATE)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_REGENERATE)
END

IF
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	OR(5)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),LONG_BOW)
		Class(LastSeenBy(Myself),SORCERER)
	Range(LastSeenBy(Myself),10)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
	See(NearestEnemyOf(Myself))
	OR(2)
		HaveSpell(CLERIC_GATE)
		Alignment(LastSeenBy(Myself),MASK_EVIL)
	HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
	!GlobalTimerNotExpired("RTLarlNumberThreeProtectionFromEvilOn","LOCALS")
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
		SetGlobalTimer("RTLarlNumberThreeProtectionFromEvilOn","LOCALS",TWENTY_MINUTES)
END

IF
	HaveSpell(CLERIC_GATE)
	See(NearestEnemyOf(Myself))
	GlobalGT("RTLarlNumberThreeProtectionFromEvilOn","LOCALS",0)
	!NumCreatureGT([EVILCUTOFF.0.0.0.0.SUMMONED],0)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_GATE)
END

IF
	HaveSpell(CLERIC_SYMBOL_FEAR)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_SYMBOL_FEAR)
END

IF
	HaveSpell(CLERIC_FIRE_STORM)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
	!Range(LastSeenBy(Myself),15)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_FIRE_STORM)
END

IF
	HaveSpell(CLERIC_CALL_LIGHTNING)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING)
END

IF
	HaveSpell(CLERIC_SLAY_LIVING)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_SLAY_LIVING)
END

IF
	HaveSpell(CLERIC_CREEPING_DOOM)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CREEPING_DOOM)
END

IF
	HaveSpell(CLERIC_HARM)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_HARM)
END

IF
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	HaveSpell(CLERIC_SOL_SEARING_ORB)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_SOL_SEARING_ORB)
END

IF
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	HaveSpell(CLERIC_CONFUSION)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CONFUSION)
END

IF
	HaveSpell(CLERIC_GREATER_COMMAND)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!HasBounceEffects(LastSeenBy(Myself))
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	!GlobalTimerNotExpired("RTLarlNumberThreeFearOn","LOCALS")
	RandomNum(2,1)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
		SetGlobalTimer("RTLarlNumberThreeFearOn","LOCALS",TWENTY_MINUTES)
END

IF
	See(NearestEnemyOf(Myself))
	Alignment(LastSeenBy(Myself),MASK_EVIL)
	HaveSpell(CLERIC_HOLY_SMITE)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_HOLY_SMITE)
END

IF
	See(NearestEnemyOf(Myself))
	Alignment(LastSeenBy(Myself),MASK_GOOD)
	HaveSpell(CLERIC_UNHOLY_BLIGHT)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)
END

IF
	HaveSpell(CLERIC_HOLD_PERSON)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
	HaveSpell(CLERIC_ENTANGLE)
	See(NearestEnemyOf(Myself))
	!HasBounceEffects(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	RandomNum(2,1)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_ENTANGLE)
END

IF
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),10)
	HaveSpell(CLERIC_SPIRITUAL_HAMMER)
	RandomNum(2,1)
	!HasItem("FIRESEED",Myself)
	!HasItem("FBLADE",Myself)
	!HasItem("SHILLE",Myself)
	!HasItem("SHAMMR",Myself)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_SPIRITUAL_HAMMER)
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
See(NearestEnemyOf(Myself))
Range(LastSeenBy(Myself),10)
HaveSpell(CLERIC_FLAME_BLADE)
RandomNum(2,1)
!HasItem("FIRESEED",Myself)
!HasItem("FBLADE",Myself)
!HasItem("SHILLE",Myself)
!HasItem("SHAMMR",Myself)
THEN
RESPONSE #100
Spell(Myself,CLERIC_FLAME_BLADE)
AttackReevaluate(LastSeenBy(Myself),45)
END

IF
See(NearestEnemyOf(Myself))
Range(LastSeenBy(Myself),10)
HaveSpell(CLERIC_SHILLELAGH)
RandomNum(2,1)
!HasItem("FIRESEED",Myself)
!HasItem("FBLADE",Myself)
!HasItem("SHILLE",Myself)
!HasItem("SHAMMR",Myself)
THEN
RESPONSE #100
Spell(Myself,CLERIC_SHILLELAGH)
AttackReevaluate(LastSeenBy(Myself),45)
END


