IF
GlobalGT("SanBeginRTF","GLOBAL",1)
InMyArea("Melicamp")
THEN
RESPONSE #100
ActionOverride("Melicamp",DestroySelf())
END

IF
GlobalGT("SanBeginRTF","GLOBAL",1)
Global("RTVisitHedge","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("RTVisitHedge","GLOBAL",1)
END

IF
Global("SanRTFPlot4","GLOBAL",5)
Global("RThintNash","BG3202",0)
THEN
RESPONSE #100
SetGlobal("RThintNash","BG3202",1)
ActionOverride("Thalantyr",Polymorph(CHICKEN))
ActionOverride("Thalantyr",SetName(@1932))
END