IF
True()
THEN
RESPONSE #100
CutSceneId(Player1)
LeaveAreaLUAPanic("AR0700","",[2753.868],4)
LeaveAreaLUA("AR0700","",[2753.868],4)
ActionOverride(Player2,LeaveAreaLUA("AR0700","",[2805.882],4))
ActionOverride(Player3,LeaveAreaLUA("AR0700","",[2791.820],4))
ActionOverride(Player4,LeaveAreaLUA("AR0700","",[2764.788],2))
ActionOverride(Player5,LeaveAreaLUA("AR0700","",[2781.716],0))
ActionOverride(Player6,LeaveAreaLUA("AR0700","",[2763.668],0))
EndCutSceneMode()
UnhideGUI()
END