IF
True()
THEN
RESPONSE #100
CutSceneId("CVSandr")
MoveViewPoint([821.287],INSTANT)
ActionOverride("RTYousha",FaceObject("CVSandr"))
Wait(4)
ReallyForceSpell("RTMonInj",CLERIC_CURE_SERIOUS_WOUNDS)
Wait(8)
ActionOverride("RTMonInj",Polymorph(MONK_FEMALE_HUMAN))
ActionOverride("RTMonInj",SetName(@1925))
Wait(4)
ActionOverride("RTMonInj",FaceObject("CVSandr"))
Wait(2)
SetGlobal("Shaheal","RTF139",2)
EndCutSceneMode()
ActionOverride("RTYouSha",StartDialogNoSet([PC]))
END

